services:
  - type: web
    name: chat-app
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y openjdk-11-jdk
      pip install -r requirements.txt
    startCommand: "gunicorn app:app"
